<?php

namespace App\Http\Requests\Ppat;

use App\Domains\Ppat\Enums\PropertyType;
use App\Policies\PropertyPolicy;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Validator;

/**
 * Validation for recording a land object (M7.3, D-121).
 *
 * ## What is required, and on whose authority
 *
 * ```text
 * property_type        four values, a closed list the ERD gives flat
 * right_type           NOT NULL in the schema; open vocabulary, free text
 * certificate_number   the legal identifier the record exists to hold
 * address              a parcel nobody can locate is not a record of a parcel
 * ```
 *
 * `property_number` is generated by the backend and is prohibited in the request.
 *
 * **`certificate_number` is deliberately not unique.** Two offices may hold records of
 * the same certificate and a certificate may be reissued — M7.1's migration says so,
 * and a unique rule here would refuse a legitimate second record.
 *
 * ## Two vocabularies, treated differently on purpose
 *
 * `property_type` is validated against {@see PropertyType} because the ERD gives four
 * values as a flat closed list. `right_type` is free text with a length limit, because
 * the ERD says *"may use stable machine codes, for example"* — a `Rule::in` on the six
 * examples would assert that Indonesian land law has six kinds of right.
 *
 * ## Refused outright rather than ignored
 *
 * `office_id` is the actor's own and `status` has no canonical vocabulary at all, so
 * neither is accepted. The refusal keys on **presence** (the D-097 pattern): an
 * interface that appears to take `status` and then drops it is worse than one that
 * says no.
 *
 * Whether this actor may create a Property, and in which Office, is
 * {@see PropertyPolicy}'s question. This class validates shape.
 */
class StorePropertyRequest extends FormRequest
{
    /**
     * System-controlled, or vocabulary that does not exist.
     */
    private const FORBIDDEN = [
        'id',
        'office_id',
        'property_number',

        // No canonical vocabulary — the ERD names the column and gives it no values,
        // so nothing writes it and nothing may send it (D-121 section 12).
        'status',

        'created_by',
        'updated_by',
        'deleted_at',
    ];

    /**
     * @return array<string, array<int, mixed>>
     */
    public function rules(): array
    {
        $rules = [
            'property_type' => ['required', 'string', Rule::in(PropertyType::values())],

            // Open vocabulary. Length only — see the class docblock.
            'right_type' => ['required', 'string', 'max:30'],

            'certificate_number' => ['required', 'string', 'max:100'],
            'certificate_date' => ['nullable', 'date'],

            // Areas are measurements somebody read off a certificate. Non-negative is
            // arithmetic, not a legal rule.
            'land_area' => ['nullable', 'numeric', 'min:0', 'max:9999999999999'],
            'building_area' => ['nullable', 'numeric', 'min:0', 'max:9999999999999'],

            'measurement_letter_number' => ['nullable', 'string', 'max:100'],
            'measurement_letter_date' => ['nullable', 'date'],

            'address' => ['required', 'string', 'max:2000'],
            'village' => ['nullable', 'string', 'max:255'],
            'district' => ['nullable', 'string', 'max:255'],
            'city' => ['nullable', 'string', 'max:255'],
            'province' => ['nullable', 'string', 'max:255'],
            'postal_code' => ['nullable', 'string', 'max:20'],

            'latitude' => ['nullable', 'numeric', 'between:-90,90'],
            'longitude' => ['nullable', 'numeric', 'between:-180,180'],
        ];

        foreach (self::FORBIDDEN as $field) {
            $rules[$field] = ['prohibited'];
        }

        return $rules;
    }

    protected function withValidator(Validator $validator): void
    {
        $validator->after(function (Validator $validator): void {
            foreach (self::FORBIDDEN as $field) {
                if (! $this->has($field) || $validator->errors()->has($field)) {
                    continue;
                }

                $validator->errors()->add(
                    $field,
                    $field === 'property_number'
                        ? 'The Property number is generated by the system.'
                        : trans('validation.prohibited', ['attribute' => str_replace('_', ' ', $field)]),
                );
            }
        });
    }

    /**
     * Ordinary Property attributes. The Action allocates the reference separately.
     *
     * @return array<string, mixed>
     */
    public function propertyAttributes(): array
    {
        return collect($this->validated())
            ->only([
                'property_type',
                'right_type',
                'certificate_number',
                'certificate_date',
                'land_area',
                'building_area',
                'measurement_letter_number',
                'measurement_letter_date',
                'address',
                'village',
                'district',
                'city',
                'province',
                'postal_code',
                'latitude',
                'longitude',
            ])
            ->all();
    }
}
