<?php

namespace App\Http\Requests\Project;

use App\Domains\Project\Enums\ProjectPriority;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Validator;

/**
 * Validation for creating a Project (M3.3, D-097).
 *
 * `title` is the only required field, and it is required **structurally** — a
 * Project with no name is unusable in a list. Nothing here is required on legal
 * grounds, and no business rule is invented: there is no check that
 * `target_completion_date` follows `opened_at`, because no canonical document
 * says a Project may not be back-dated or planned in an unusual order.
 *
 * **Every system-controlled field is `prohibited`, not silently dropped.** An
 * interface that appears to accept `office_id` and then ignores it is worse than
 * one that refuses: the caller believes the Project went somewhere it did not.
 * Refusing loudly is the whole reason this list exists rather than relying on
 * `$fillable` alone.
 *
 * `office_id` deserves its own note. It is not merely absent from the shape — it
 * is refused, because "create in another Office" is the exact thing an
 * `ALL`-scoped actor might reasonably expect to be able to do. `ALL` is
 * cross-office *reach* over existing Projects (D-088); creation is always in the
 * actor's own Office (D-097).
 *
 * `completed_at` is prohibited too: a Project cannot be completed before it
 * exists, and exposing the field at creation would invite a date with no event
 * behind it.
 *
 * The refusal keys on **presence**, not on emptiness — see `withValidator()`.
 */
class StoreProjectRequest extends FormRequest
{
    /**
     * System-controlled, refused outright.
     */
    private const FORBIDDEN = [
        'id',
        'office_id',
        'project_number',
        'status',
        'pic_user_id',
        'created_by',
        'updated_by',
        'deleted_at',
        'completed_at',
    ];

    /**
     * @return array<string, array<int, mixed>>
     */
    public function rules(): array
    {
        $rules = [
            'title' => ['required', 'string', 'max:255'],
            'description' => ['sometimes', 'nullable', 'string'],
            'priority' => ['sometimes', 'nullable', Rule::enum(ProjectPriority::class)],
            'opened_at' => ['sometimes', 'nullable', 'date'],
            'target_completion_date' => ['sometimes', 'nullable', 'date'],
        ];

        foreach (self::FORBIDDEN as $field) {
            $rules[$field] = ['prohibited'];
        }

        return $rules;
    }

    /**
     * Refuse a system-controlled key that is *present*, whatever its value.
     *
     * `prohibited` is not sufficient on its own: Laravel reads it as "missing or
     * empty", so `{"status": null}` satisfies it and the request answers 201.
     * Nothing would be written either way — `projectAttributes()` intersects an
     * explicit allow-list and the model keeps these columns out of `$fillable` —
     * but the caller would be told an instruction was accepted when it was
     * discarded. That is the silent no-op this class exists to prevent, and the
     * empty case is no less silent than the non-empty one.
     */
    protected function withValidator(Validator $validator): void
    {
        $validator->after(function (Validator $validator): void {
            foreach (self::FORBIDDEN as $field) {
                // `prohibited` has already spoken for a non-empty value; adding
                // a second message for the same field would only be noise.
                if (! $this->has($field) || $validator->errors()->has($field)) {
                    continue;
                }

                $validator->errors()->add($field, $this->messageFor($field));
            }
        });
    }

    private function messageFor(string $field): string
    {
        return $this->messages()[$field.'.prohibited']
            ?? trans('validation.prohibited', ['attribute' => str_replace('_', ' ', $field)]);
    }

    /**
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'office_id.prohibited' => 'A Project is created in your own Office.',
            'project_number.prohibited' => 'The Project number is generated by the system.',
            'status.prohibited' => 'A new Project starts as OPEN.',
            'pic_user_id.prohibited' => 'Assign a person in charge after the Project exists.',
        ];
    }

    /**
     * The ordinary attributes the create Action may fill.
     *
     * @return array<string, mixed>
     */
    public function projectAttributes(): array
    {
        return array_intersect_key($this->validated(), array_flip([
            'title', 'description', 'priority', 'opened_at', 'target_completion_date',
        ]));
    }
}
