<?php

namespace App\Http\Requests\Matter;

use App\Domains\Project\Enums\ProjectPriority;
use App\Policies\MatterPolicy;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Validator;

/**
 * Validation for creating a Matter (M4.4, D-109).
 *
 * `project_id` and `title` are the only required fields, and both are required
 * **structurally**: a Matter is always a child of a Project (D-099), and one with
 * no name is unusable in a list. Nothing here is required on legal grounds, and no
 * business rule is invented — there is no check that `target_completion_date`
 * follows `opened_at`, because no canonical document says a Matter may not be
 * back-dated or planned in an unusual order.
 *
 * **Every system-controlled field is `prohibited`, not silently dropped**, and
 * the refusal keys on **presence** rather than emptiness — the M3.3 pattern
 * (D-097), for the same reason: an interface that appears to accept `domain` and
 * then ignores it is worse than one that refuses, because the caller believes the
 * Matter went somewhere it did not.
 *
 * Three of them deserve their own note.
 *
 * **`domain` is refused because the route decides it** (D-101). Accepting it in
 * the body would put the permission namespace under the caller's control, which
 * is precisely the authorization shape the M3 lock flagged and M4.0 declined.
 *
 * **`office_id` is refused because the parent Project decides it** (D-099). Unlike
 * Project, where creation is always in the actor's own Office, a Matter inherits —
 * so there is nothing here for a caller to choose even in principle.
 *
 * **`pic_user_id` is refused because assignment is its own capability.** Allowing
 * it at creation would let `*.matters.create` silently perform an act
 * `*.matters.assign` was granted separately to control.
 *
 * The parent Project's eligibility — reachable under `projects.view`, in the
 * actor's own Office, and not archived — is decided by {@see MatterPolicy},
 * not here. This class validates shape; the Policy validates authority.
 */
class StoreMatterRequest extends FormRequest
{
    /**
     * System-controlled, refused outright.
     */
    private const FORBIDDEN = [
        'id',
        'office_id',
        'domain',
        'matter_number',
        'status',
        'pic_user_id',
        'created_by',
        'updated_by',
        'deleted_at',
        'completed_at',
        'current_stage_id',
    ];

    /**
     * @return array<string, array<int, mixed>>
     */
    public function rules(): array
    {
        $rules = [
            'project_id' => ['required', 'string'],
            'service_type_id' => ['sometimes', 'nullable', 'string'],
            'title' => ['required', 'string', 'max:255'],
            'priority' => ['sometimes', 'nullable', Rule::enum(ProjectPriority::class)],
            'opened_at' => ['sometimes', 'nullable', 'date'],
            'target_completion_date' => ['sometimes', 'nullable', 'date'],
            'notes' => ['sometimes', 'nullable', 'string'],
        ];

        foreach (self::FORBIDDEN as $field) {
            $rules[$field] = ['prohibited'];
        }

        return $rules;
    }

    /**
     * Refuse a system-controlled key that is *present*, whatever its value.
     *
     * `prohibited` is not sufficient on its own: Laravel reads it as "missing or
     * empty", so `{"domain": null}` satisfies it and the request answers 201.
     * Nothing would be written either way, but the caller would be told an
     * instruction was accepted when it was discarded.
     */
    protected function withValidator(Validator $validator): void
    {
        $validator->after(function (Validator $validator): void {
            foreach (self::FORBIDDEN as $field) {
                if (! $this->has($field) || $validator->errors()->has($field)) {
                    continue;
                }

                $validator->errors()->add($field, $this->messageFor($field));
            }
        });
    }

    private function messageFor(string $field): string
    {
        return $this->messages()[$field.'.prohibited']
            ?? trans('validation.prohibited', ['attribute' => str_replace('_', ' ', $field)]);
    }

    /**
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'domain.prohibited' => 'The Matter domain comes from the address you are posting to.',
            'office_id.prohibited' => 'A Matter belongs to the Office of its Project.',
            'matter_number.prohibited' => 'The Matter number is generated by the system.',
            'status.prohibited' => 'A new Matter starts as OPEN.',
            'pic_user_id.prohibited' => 'Assign the person in charge after the Matter exists.',
            'completed_at.prohibited' => 'A Matter cannot be completed before it exists.',
            'current_stage_id.prohibited' => 'Workflow stages do not exist yet.',
        ];
    }

    /**
     * The ordinary attributes, and only those.
     *
     * An explicit allow-list rather than `except()`: a field added to the payload
     * later is excluded until somebody names it here.
     *
     * @return array<string, mixed>
     */
    public function matterAttributes(): array
    {
        return array_intersect_key($this->validated(), array_flip([
            'title',
            'priority',
            'opened_at',
            'target_completion_date',
            'notes',
        ]));
    }

    public function projectId(): string
    {
        return (string) $this->validated()['project_id'];
    }

    public function serviceTypeId(): ?string
    {
        $value = $this->validated()['service_type_id'] ?? null;

        return $value === null ? null : (string) $value;
    }
}
